import Link from 'next/link';
import { Control } from './Control';
import './globals.css';

export const metadata = {
  title: 'My First Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
  // console.log('run layout');
  const resp = await fetch('http://localhost:9999/topics', {
    cache: 'no-store',
  });
  const topics = await resp.json();
  console.log(topics);
  return (
    <html lang='en'>
      <body>
        <div>
          <input type='text' placeholder='search' />
          <h1>
            <Link href='/'>WEB</Link>
          </h1>
          <ol>
            {topics.map((topic) => {
              return (
                <li key={topic.id}>
                  <Link href={`/read/${topic.id}`}>{topic.title}</Link>
                </li>
              );
            })}
          </ol>
          {children}
          <Control />
        </div>
      </body>
    </html>
  );
}
